/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiDiagnosticsRouteImport } from './routes/ai-diagnostics'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as DigitalTwinRouteImport } from './routes/digital-twin'
import { Route as LiveMonitoringRouteImport } from './routes/live-monitoring'
import { Route as PlantOverviewRouteImport } from './routes/plant-overview'
import { Route as PredictiveMaintenanceRouteImport } from './routes/predictive-maintenance'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SystemArchitectureRouteImport } from './routes/system-architecture'
import { Route as EquipmentIndexRouteImport } from './routes/equipment.index'
import { Route as EquipmentIdRouteImport } from './routes/equipment.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiDiagnosticsRoute = AiDiagnosticsRouteImport.update({
  id: '/ai-diagnostics',
  path: '/ai-diagnostics',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const DigitalTwinRoute = DigitalTwinRouteImport.update({
  id: '/digital-twin',
  path: '/digital-twin',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveMonitoringRoute = LiveMonitoringRouteImport.update({
  id: '/live-monitoring',
  path: '/live-monitoring',
  getParentRoute: () => rootRouteImport,
} as any)
const PlantOverviewRoute = PlantOverviewRouteImport.update({
  id: '/plant-overview',
  path: '/plant-overview',
  getParentRoute: () => rootRouteImport,
} as any)
const PredictiveMaintenanceRoute = PredictiveMaintenanceRouteImport.update({
  id: '/predictive-maintenance',
  path: '/predictive-maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemArchitectureRoute = SystemArchitectureRouteImport.update({
  id: '/system-architecture',
  path: '/system-architecture',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipmentIndexRoute = EquipmentIndexRouteImport.update({
  id: '/equipment/',
  path: '/equipment/',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipmentIdRoute = EquipmentIdRouteImport.update({
  id: '/equipment/$id',
  path: '/equipment/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-diagnostics': typeof AiDiagnosticsRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/digital-twin': typeof DigitalTwinRoute
  '/live-monitoring': typeof LiveMonitoringRoute
  '/plant-overview': typeof PlantOverviewRoute
  '/predictive-maintenance': typeof PredictiveMaintenanceRoute
  '/settings': typeof SettingsRoute
  '/system-architecture': typeof SystemArchitectureRoute
  '/equipment/$id': typeof EquipmentIdRoute
  '/equipment/': typeof EquipmentIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-diagnostics': typeof AiDiagnosticsRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/digital-twin': typeof DigitalTwinRoute
  '/live-monitoring': typeof LiveMonitoringRoute
  '/plant-overview': typeof PlantOverviewRoute
  '/predictive-maintenance': typeof PredictiveMaintenanceRoute
  '/settings': typeof SettingsRoute
  '/system-architecture': typeof SystemArchitectureRoute
  '/equipment/$id': typeof EquipmentIdRoute
  '/equipment': typeof EquipmentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-diagnostics': typeof AiDiagnosticsRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/digital-twin': typeof DigitalTwinRoute
  '/live-monitoring': typeof LiveMonitoringRoute
  '/plant-overview': typeof PlantOverviewRoute
  '/predictive-maintenance': typeof PredictiveMaintenanceRoute
  '/settings': typeof SettingsRoute
  '/system-architecture': typeof SystemArchitectureRoute
  '/equipment/$id': typeof EquipmentIdRoute
  '/equipment/': typeof EquipmentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-diagnostics'
    | '/alerts'
    | '/analytics'
    | '/digital-twin'
    | '/live-monitoring'
    | '/plant-overview'
    | '/predictive-maintenance'
    | '/settings'
    | '/system-architecture'
    | '/equipment/$id'
    | '/equipment/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-diagnostics'
    | '/alerts'
    | '/analytics'
    | '/digital-twin'
    | '/live-monitoring'
    | '/plant-overview'
    | '/predictive-maintenance'
    | '/settings'
    | '/system-architecture'
    | '/equipment/$id'
    | '/equipment'
  id:
    | '__root__'
    | '/'
    | '/ai-diagnostics'
    | '/alerts'
    | '/analytics'
    | '/digital-twin'
    | '/live-monitoring'
    | '/plant-overview'
    | '/predictive-maintenance'
    | '/settings'
    | '/system-architecture'
    | '/equipment/$id'
    | '/equipment/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiDiagnosticsRoute: typeof AiDiagnosticsRoute
  AlertsRoute: typeof AlertsRoute
  AnalyticsRoute: typeof AnalyticsRoute
  DigitalTwinRoute: typeof DigitalTwinRoute
  LiveMonitoringRoute: typeof LiveMonitoringRoute
  PlantOverviewRoute: typeof PlantOverviewRoute
  PredictiveMaintenanceRoute: typeof PredictiveMaintenanceRoute
  SettingsRoute: typeof SettingsRoute
  SystemArchitectureRoute: typeof SystemArchitectureRoute
  EquipmentIdRoute: typeof EquipmentIdRoute
  EquipmentIndexRoute: typeof EquipmentIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-diagnostics': {
      id: '/ai-diagnostics'
      path: '/ai-diagnostics'
      fullPath: '/ai-diagnostics'
      preLoaderRoute: typeof AiDiagnosticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/digital-twin': {
      id: '/digital-twin'
      path: '/digital-twin'
      fullPath: '/digital-twin'
      preLoaderRoute: typeof DigitalTwinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-monitoring': {
      id: '/live-monitoring'
      path: '/live-monitoring'
      fullPath: '/live-monitoring'
      preLoaderRoute: typeof LiveMonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plant-overview': {
      id: '/plant-overview'
      path: '/plant-overview'
      fullPath: '/plant-overview'
      preLoaderRoute: typeof PlantOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/predictive-maintenance': {
      id: '/predictive-maintenance'
      path: '/predictive-maintenance'
      fullPath: '/predictive-maintenance'
      preLoaderRoute: typeof PredictiveMaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system-architecture': {
      id: '/system-architecture'
      path: '/system-architecture'
      fullPath: '/system-architecture'
      preLoaderRoute: typeof SystemArchitectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipment/': {
      id: '/equipment/'
      path: '/equipment'
      fullPath: '/equipment/'
      preLoaderRoute: typeof EquipmentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipment/$id': {
      id: '/equipment/$id'
      path: '/equipment/$id'
      fullPath: '/equipment/$id'
      preLoaderRoute: typeof EquipmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiDiagnosticsRoute: AiDiagnosticsRoute,
  AlertsRoute: AlertsRoute,
  AnalyticsRoute: AnalyticsRoute,
  DigitalTwinRoute: DigitalTwinRoute,
  LiveMonitoringRoute: LiveMonitoringRoute,
  PlantOverviewRoute: PlantOverviewRoute,
  PredictiveMaintenanceRoute: PredictiveMaintenanceRoute,
  SettingsRoute: SettingsRoute,
  SystemArchitectureRoute: SystemArchitectureRoute,
  EquipmentIdRoute: EquipmentIdRoute,
  EquipmentIndexRoute: EquipmentIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
